version: "v3"
services:
  logstash:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./agent.env
      - ./vendor-config.env
    volumes:
      - ./config:/usr/share/logstash/config
      - ./pipelines:/usr/share/logstash/pipelines
      - ./ssl:/usr/share/logstash/ssl
      # - logstash_data:/usr/share/logstash/data
volumes:
  logstash_data: