input {
  jdbc {
    jdbc_connection_string => "jdbc:sqlserver://${DB_SERVER}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true"
    jdbc_user => "${DB_USER}"
    jdbc_password => "${DB_PASSWORD}"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    statement => "SELECT * FROM ${DB_NAME}.${DB_SCHEMA}.ct00"
    schedule => "${SCHEDULE}"
    lowercase_column_names => false
    jdbc_validate_connection => true
  }
}



filter {
  mutate {
    add_field => {
      "pipeline_id" => "${PIPELINE_ID}"
      "src_tbl_name" => "ct00"
    }
  }
  ruby {
    code => '
      original = event.to_hash.clone
      original.delete("@version")
      original.delete("@timestamp")
      event.set("original", original)
      event.to_hash.keys.each { |k| event.remove(k) unless ["original", "@timestamp"].include?(k) }
    '
  }
}

output {
  kafka {
    codec => json
    topic_id => "${DS_OrgID_WorkspaceID}"
    bootstrap_servers => "${KAFKA_BOOTSTRAP_SERVERS}"
    security_protocol => "SSL"
    ssl_truststore_location => "/usr/share/logstash/ssl/ca.jks"
    ssl_truststore_password => "${TRUSTSTORE_PASSWORD}"
    ssl_keystore_location => "/usr/share/logstash/ssl/client.jks"
    ssl_keystore_password => "${KEYSTORE_PASSWORD}"
    ssl_endpoint_identification_algorithm => ""
    codec => json
    compression_type => "gzip"
}
}